services:
  mlflow:
    build: ./mlflow_server
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    depends_on:
      - mlflow

  streamlit:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8501:8501"
    environment:
      API_URL: http://api:8000
    depends_on:
      - api

volumes:
  mlflow_data: